language: node_js
node_js:
  - 'stable'
  - '0.12'
  - '0.10'
sudo: false
cache:
  directories:
    - node_modules
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.x.x && cat ./coverage/lcov.info | coveralls"
